Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cine.Models
{
    [Table("Member")]
    public class Member
    {
        [Required]
        [Column("Name")]
        [Key]
        [MaxLength(60)]
        public string Name { get; set; }
        
        [Required]
        [Column("Email")]
        [MaxLength(70)]
        public string Email { get; set; }
        
        [Required]
        [Column("Card")]
        [MaxLength(100)]
        public string Card { get; set; }
        
        [Required]
        [Column("Code")]
        [MaxLength(100)]
        public string Code { get; set; }
        
        [Required]
        [Column("Points")]
        public int Points { get; set; }
    }
}

Models/Producer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cine.Models
{
    [Table("Producer")]
    public class Producer
    {
        [Key]
        public int ProducerId { get; set; }
        
        [Required]
        [Column("Name")]
        [MaxLength(60)]
        public string Name { get; set; }
        
        [Required]
        [Column("Country")]
        [MaxLength(50)]
        public string Country { get; set; }
        
        [Required]
        [Column("Age")]
        public int Age { get; set; }
        
        [Column("Movies")]
        public virtual ICollection<Movie> Movies { get; set; }
    }
}

Models/Promotion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cine.Models
{
    [Table("Promotion")]
    public class Promotion
    {
        [Required]
        [Column("IdD")]
        [Key]
        public int IdD { get; set; }
        
        [Required]
        [Column("Discount")]
        public decimal Discount { get; set; }
        
        [Required]
        [Column("Description")]
        [MaxLength(300)]
        public string Description { get; set; }
    }
}

Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Cine.Models;
using Cine.Tools;

namespace Cine.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        //public IActionResult Films(int page = 1, string search_by = "Title", string order_by = "Title", string search = "")
        //{
        //    GenericPaginator<Cine.Models.Movie> _MoviePaginator;
            
        //    int _TotalRegistry = _DbContext.Movies.Count();
        //    if (search_by == "Title")_Movies = _DbContext.Movies.Where(x => x.Title.StartsWith(search)).ToList();
        //    else if (search_by == "Country") _Movies = _DbContext.Movies.Where(x => x.Country.StartsWith(search)).ToList();
        //    else if (search_by == "Category") _Movies = _DbContext.Movies.Where(x => x.Category.StartsWith(search)).ToList();

        //    if (order_by == "Title")
        //        _Movies = _DbContext.Movies.OrderBy(x => x.Title)
        //                                 .Skip((page - 1) * _RegistrysPerPage)
        //                                 .Take(_RegistrysPerPage)
        //                                 .ToList();
            
        //    else if (order_by == "Year")
        //        _Movies = _DbContext.Movies.OrderBy(x => x.Year)
        //                                 .Skip((page - 1) * _RegistrysPerPage)
        //                                 .Take(_RegistrysPerPage)
        //                                 .ToList();
            
        //    else if (order_by == "Duration")
        //        _Movies = _DbContext.Movies.OrderBy(x => x.Duration)
        //                                 .Skip((page - 1) * _RegistrysPerPage)
        //                                 .Take(_RegistrysPerPage)
        //                                 .ToList();


        //    var _TotalPages = (int)Math.Ceiling((double)_TotalRegistry / _RegistrysPerPage);
        //    // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
        //    _MoviePaginator = new GenericPaginator<Cine.Models.Movie>()
        //    {
        //        RegistrysPerPage = _RegistrysPerPage,
        //        TotalRegistrys = _TotalRegistry,
        //        TotalPages = _TotalPages,
        //        ActualPage = page,
        //        Result = _Movies
        //    };
        //    // Enviamos a la Vista la 'Clase de paginación'
        //    return View(_MoviePaginator);
        //}
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cine.Models;
using Cine.ModelsRepository;
using Cine.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace Cine.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IGetRepository<Show> _showRepository;
        private readonly IGetRepository<Movie> _movieRepository;
        private readonly IGetRepository<Cinema> _cinemaRepository;
        private readonly ITicketRepository _ticketRepository;
        private readonly IGetRepository<Discount> _discountRepository;
        private readonly CineDbContext _context;


        public ManagerController(IGetRepository<Show> showRepository, IGetRepository<Movie> movieRepository,
            IGetRepository<Cinema> cinemaRepository,
            ITicketRepository ticketRepository,
            IGetRepository<Discount> discountRepository,
            CineDbContext context)
        {
            _ticketRepository = ticketRepository;
            _showRepository = showRepository;
            _movieRepository = movieRepository;
            _cinemaRepository = cinemaRepository;
            _discountRepository = discountRepository;
            _context = context;
        }
        // GET
        public IActionResult Main()
        {
            return View();
        }
        [HttpPost]
       public IActionResult Main(IFormCollection querys)
        {

            if (querys.ContainsKey("filmsCriteria"))
            {
                if (querys["filmsCriteria"] == "liked")
                {
                    IEnumerable<Show> shows = _context.Shows.OrderBy(show => _ticketRepository.GetShowTicekts(show.ShowId).Count()).Take(10);
                    List<Movie> m = new List<Movie>();
                    foreach (var s in shows)
                    {
                        m.Append(_context.Movies.Find(s.MovieId));
                    }

                    ViewBag.Query = m;
                    //Aki va la query de las 10 peliculas con mas tickets vendidios
                }
                if (querys["filmsCriteria"] == "economic")
                {
                    IEnumerable<Show> shows = _context.Shows.OrderBy(show => _ticketRepository.GetShowTicekts(show.ShowId).Count() * show.Price).Take(10);
                    List<Movie> m = new List<Movie>();
                    foreach (var s in shows)
                    {
                        m.Append(_context.Movies.Find(s.MovieId));
                    }

                    ViewBag.Query = m;
                    //Aki va la query de las 10 peliculas q mas money recaudaron
                }
            }
            if (querys.ContainsKey("statics_by"))
            {
                string value = querys["Value"];
                if(querys["statics_by"] == "category")
                {
                    IEnumerable<Show> shows = _context.Shows.OrderBy(show => _context.Movies.Find(show.MovieId).Category == value);
                    int count = 0;
                    foreach (var s in shows)
                    {
                        count += _ticketRepository.GetShowTicekts(s.ShowId).Count();
                    }

                    ViewBag.Query = count;
                    //Aqui va la query de todos los tickets q se han vendido para pelicas q su categoria 
                    //coicide con el value
                }
                if (querys["statics_by"] == "film")
                {
                    IEnumerable<Show> shows = _context.Shows.OrderBy(show => _context.Movies.Find(show.MovieId).Title == value);
                    int count = 0;
                    foreach (var s in shows)
                    {
                        count += _ticketRepository.GetShowTicekts(s.ShowId).Count();
                    }

                    ViewBag.Query = count;
                    //Aqui va la query de los tickets q se han vendido para peliculas con el titilo q esta en value
                }
                if (querys["statics_by"] == "rating")
                {
                    IEnumerable<Show> shows = _context.Shows.OrderBy(show => _ticketRepository.GetShowTicekts(show.ShowId).Count()).Take(1);
                    Show s = null;
                    foreach (var ss in  shows)
                    {
                        s = ss;
                    }
                    
                    ViewBag.Query = _ticketRepository.GetShowTicekts(s.ShowId).Count();
                    //Aki va la query de los tickets de la pelicula con mas tickets vendidos
                }
            }

            return View();
        }
    }
}

Controllers/ProducerController.cs
using System;
using System.Linq;
using Cine.Models;
using Cine.ModelsRepository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Cine.Controllers
{
    public class ProducerController : Controller
    {
        // GET
        private readonly IGetRepository<Actor> _actorRepository;
        private readonly IGetRepository<Director> _directorRepository;
        private readonly IGetRepository<Movie> _movieRepository;

        public ProducerController(IGetRepository<Actor> actorRepository,
            IGetRepository<Director> directorRepository,
            IGetRepository<Movie> movieRepository)
        {
            _actorRepository = actorRepository;
            _directorRepository = directorRepository;
            _movieRepository = movieRepository;
        }

        [HttpPost]
        public IActionResult CreateActor(Actor obj)
        {
            _actorRepository.Add(obj);
            return RedirectToAction("ProducerList", "Producer");
        }
        [HttpPost]
        public IActionResult CreateDirector(Director obj)
        {
            _directorRepository.Add(obj);
            return RedirectToAction("ProducerList", "Producer");
        }
        [HttpPost]
        public IActionResult UpdateDirector(Director obj)
        {
            _directorRepository.Update(obj);
            return RedirectToAction("ProducerList", "Producer");
        }
        public IActionResult UpdateActor(Actor obj)
        {
            _actorRepository.Update(obj);
            return RedirectToAction("ProducerList", "Producer");
        }

        public IActionResult ProducerList()
        {
            IEnumerable<Actor> actors = _actorRepository.GetAllObj();
            IEnumerable<Director> directors = _directorRepository.GetAllObj();
            IEnumerable<Movie> movies = _movieRepository.GetAllObj();
            ViewBag.Actors = actors;
            ViewBag.Directors = directors;
            ViewBag.Movies = movies;
            ViewBag.ActorsCount = actors?.Count() ?? 0;
            ViewBag.DirectorsCount = directors?.Count() ?? 0;
            ViewBag.MoviesCount = movies?.Count() ?? 0;
            return View();
        }
    }
}

Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cine.Models;
using Cine.ModelsRepository;
using Cine.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace Cine.Controllers
{
    public class ShowController : Controller
    {
        private readonly IGetRepository<Show> _showRepository;
        private readonly IGetRepository<Movie> _movieRepository;
        private readonly IGetRepository<Cinema> _cinemaRepository;
        private readonly ITicketRepository _ticketRepository;
        private readonly IGetRepository<Discount> _discountRepository;


        public ShowController(IGetRepository<Show> showRepository,IGetRepository<Movie> movieRepository,
            IGetRepository<Cinema> cinemaRepository,
            ITicketRepository ticketRepository,
            IGetRepository<Discount> discountRepository)
        {
            _ticketRepository = ticketRepository;
            _showRepository = showRepository;
            _movieRepository = movieRepository;
            _cinemaRepository = cinemaRepository;
            _discountRepository = discountRepository;
        }
        
        [HttpPost]
        public IActionResult Create(Show obj)
        {
            _showRepository.Add(obj);
            return RedirectToAction("ShowList", "Show");
        }
        public IActionResult Update(Show obj)
        {
            _showRepository.Update(obj);
            return RedirectToAction("ShowList", "Show");
        }

        public IActionResult MainShowDetails(int id)
        {
            
            Show s = _showRepository.GetObj(id);
            ViewBag.Movie = _movieRepository.GetObj(s.MovieId);
            Cinema cinema = _cinemaRepository.GetObj(s.CinemaId);
            ViewBag.Cinema = cinema;
            IEnumerable<Ticket> tickets = _ticketRepository.GetShowTicekts(id);
            bool[] seats = new bool[cinema.NumberOfSeats];
            for (int i = 0; i < cinema.NumberOfSeats; i++)
                seats[i] = true;
            foreach (var t in  tickets)
                seats[t.SeatNumber] = false;
            ViewBag.Seats = seats;
            return View(s);
        }
        [HttpPost]
        public IActionResult MainShowDetails(IFormCollection seatsform)
        {
            int withDiscounts = 0;
            if (seatsform.Keys.Contains("discount")) withDiscounts = int.Parse(seatsform["discount"]);
            int showId = int.Parse(seatsform["id"]);
            List<int> seats = new List<int>();
            int item = 0;
            foreach(var t in seatsform.Keys)
            {
                if (Int32.TryParse(t, out item))
                {
                    seats.Add(item);
                }
            }   
            
            //En seats estan los ints de los asientos whitdiscount la cantidad de tickets q tiene descuentos y el showid del show
            Show show = _showRepository.GetObj(showId);
            Discount d;
            if (show.DiscountId != null)
                d = _discountRepository.GetObj(show.DiscountId);
            else
                d = null;
            List<Ticket> buyed = new List<Ticket>();
            foreach (var s in seats)
            {
                if (withDiscounts > 0)
                {
                    decimal percent = d.Percent;
                    Ticket newTicket = new Ticket
                    {
                        Price = show.Price - ((show.Price * percent) / 100),
                        Discount = d,
                        DiscountId = d.DiscountId,
                        SeatNumber = s,
                        Show = show,
                        ShowId = show.ShowId,
                    };
                    _ticketRepository.Add(newTicket);
                    buyed.Add(newTicket);
                }
                else
                {
                    Ticket newTicket = new Ticket
                    {
                        Price = show.Price,
                        SeatNumber = s,
                        Show = show,
                        ShowId = show.ShowId,
                    };
                    _ticketRepository.Add(newTicket);
                    buyed.Add(newTicket);
                }
            }


            return RedirectToAction("MainShows", "Show");
        }
        
        public IActionResult ShowList()
        {
            IEnumerable<Show> shows = _showRepository.GetAllObj();
            IEnumerable<Movie> movies = _movieRepository.GetAllObj();
            IEnumerable<Cinema> cinemas = _cinemaRepository.GetAllObj();
            IEnumerable<Discount> discounts = _discountRepository.GetAllObj();
            ViewBag.Shows = shows;
            ViewBag.ShowsCount = shows?.Count() ?? 0;
            ViewBag.Movies = movies;
            ViewBag.MoviesCount = movies?.Count() ?? 0;
            ViewBag.Cinemas = cinemas;
            ViewBag.CinemasCount = cinemas?.Count() ?? 0;
            ViewBag.Discounts = discounts;
            ViewBag.DiscountsCount = discounts?.Count() ?? 0;
            return View();
        }

        //Regular user view (Main)
        public IActionResult MainShows(int page = 1)
        {
            IEnumerable<Show> shows = _showRepository.GetAllObj();
            shows = shows.Where(x => x.Date > DateTime.Now);
            shows = shows.OrderBy(x => x.Date);
            IEnumerable<Movie> movies = _movieRepository.GetAllObj();
            ViewBag.Shows = shows;
            ViewBag.ShowsCount = shows?.Count() ?? 0;
            ViewBag.Movies = movies;
            ViewBag.MoviesCount = movies?.Count() ?? 0;
            return View();
        }
    }
}

Views/Manager/Main.cshtml
@{
    Layout = "~/Views/Manager/_Layout.cshtml";
}
<br>
<div class="card bg-dark" style="opacity: 80%; color: white">
    <div class="row" style="margin: 10px">
        <div class="col-6">
            <div class="card-header">Statistics</div>
            <form method="post">

                <div class="form-group row">
                    <div class="col-4">
                        <!--<span asp-validation-for="CinemaId"></span>-->
                    </div>
                    <div class="col-4">
                        <label for="example-time-input" class="col-form-label">Date</label>
                        <input name="date" class="form-control" type="Date">
                    </div>
                    <div class="col-4">
                        <label for="example-time-input" class="col-form-label">Search By:</label>
                        <select name="statics_by" id="criterion" class="form-select form-control" aria-label="Default select example">
                            <option value="category">Category</option>
                            <option value="film">Film</option>
                            <option value="rating">Rating</option>
                        </select>
                        <br>
                        <input name="Value" class="form-control" type="text" />
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p class="text-black-dark">Number of Tickets: @ViewBag.Query </p>
                    </div>
                </div>
                <button type="submit" class="bg-blue-500 ml-4 mt-4 hover:bg-blue-200 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-500 rounded">Search</button>

            </form>
        </div>
        <div class="col-6">
            <div class="card-header">Films to show</div>
            <div class="form-group row">
                <form method="post">
                    <div class="form-group">
                        <label for="example-time-input" class="col-form-label">Search: </label>
                        <select name="filmsCriteria" id="criterion" class="form-select form-control" aria-label="Default select example">
                            <option value="liked">Most liked movies</option>
                            <option value="economic">Economic gain</option>
                        </select>
                        <br>
                        <button type="submit" class="bg-blue-500 hover:bg-blue-200 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-500 rounded">Search</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

Views/Manager/_Films.cshtml
@model Movie;
<div class=" w-full">
    <div class="flex flex-col items-center justify-center">
        <p class="text-2xl text-center font-bold m-5">Películas</p>
        <table class="rounded-t-lg m-5 w-5/6 mx-auto bg-gray-200 text-gray-800">
            <tr class="text-left border-b-2 border-gray-300">
                <th class="px-4 py-3">Título</th>
                <th class="px-4 py-3">Género</th>
                <th class="px-4 py-3">Categoría</th>
                <th class="px-4 py-3">Duración</th>
                <th class="px-4 py-3">Año</th>
                <th class="px-4 py-3">País</th>
                <th class="px-4 py-3">Sinopsis</th>
                <th class="px-4 py-3">Acción</th>
            </tr>
            <tbody>
                                                                
            </tbody>
        </table>
        <button data-modal="formFilm" class="modal-trigger bg-red-500 hover:bg-red-200 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-500 rounded">Agregar Película</button>
        <div id="formFilm" class="modal-wrapper">
            <div class="overlay close-modal"></div>
            <div class="modal modal-centered">
                <div class="modal-content shadow-lg p-5">
                    <div class="border-b p-2 pb-3 pt-0 mb-4">
                        <div class="flex justify-between items-center">
                            Agregar Película
                        </div>
                    </div>
                    <!-- Modal content -->
                    <form method="post" id="form_id" class="w-full" asp-controller="Movie" asp-action="Create">
                        <div class="form-group row">
                            <div class="col-10">
                                <input class="form-control" placeholder="Título" type="text" asp-for="Title">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <input class="form-control" placeholder="Categoría" type="text" asp-for="Category">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <input class="form-control" placeholder="Género" type="text" asp-for="Genre">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <input class="form-control" type="text" placeholder="Sinopsis" asp-for="Synopsis">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <input class="form-control" type="text" placeholder="País" asp-for="Country">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <label>Duración</label>
                                <input class="form-control" type="time" placeholder="Duración" asp-for="Duration">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10">
                                <label>Año</label>
                                <input class="form-control" type="number" value="2021" placeholder="Año" asp-for="Year">
                            </div>
                        </div>
                        <div class="mt-5">
                            <input type="submit" class="bg-green-500 hover:bg-green-800 text-white font-bold py-2 px-4 rounded" value="Crear"/>
                            <span class="close-modal cursor-pointer bg-red-200 hover:bg-red-500 text-red-900 font-bold py-2 px-4 rounded">
                                Cerrar
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Manager/_Layout.cshtml
@inject SignInManager<TheaterUser> _signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="author" content="name">
    <meta name="description" content="description here">
    <meta name="keywords" content="keywords,here">
    <link rel="stylesheet" href="~/css/manager.css">
    <link rel="stylesheet" href="~/lib/tailwindcss/dist/tailwind.min.css">
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/all.css">
    <style>
        body{background: #1D4350;  /* fallback for old browsers */
             background: -webkit-linear-gradient(to right, #A43931, #1D4350);  /* Chrome 10-25, Safari 5.1-6 */
             background: linear-gradient(to right, #A43931, #1D4350); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}

        .toggle_dot {
            top: -.25rem;
            transition: all 0.3s ease-in-out;
        }

        input:checked ~ .toggle_dot {
            transform: translateX(100%);
            background-color: #0082c8;
        }

        .bg-gradient {
            background: #667db6;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #667db6, #0082c8, #0082c8, #667db6);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #667db6, #0082c8, #0082c8, #667db6);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .bg-gradient-base {
            background-color: #0082c8;
        }

        .font-work-sans {
            font-family: 'Work Sans', sans-serif;
        }

        :root {
            --shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
            --ring-offset-shadow: 0 0 #0000;
            --ring-shadow: 0 0 #0000;
        }

        .card_open {
            animation-duration: 500ms;
            animation-name: card_open;
        }

        @@keyframes card_open {
            from {
                height: 1%;
                box-shadow: var(--shadow);
            }

            to {
                height: 100%;
                box-shadow: var(--ring-offset-shadow,0 0 #0000),var(--ring-shadow,0 0 #0000),var(--shadow);
            }
        }
    </style>
</head>
<body class="bg-white font-sans leading-normal tracking-normal">
<nav class="flex absolute top-0 items-center justify-between flex-wrap bg-dark shadow-2xl p-8 fixed w-full z-40 top-0">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <a class="text-white no-underline hover:text-white hover:no-underline" asp-controller="Main" asp-action="Index">
            <span class="text-4xl pl-2 font-bold"><i class="em em-grinning"></i>Cine+</span>
        </a>
        <a class="text-white no-underline hover:text-white hover:no-underline" asp-controller="Manager" asp-action="Main">
            <span class="text-2xl pl-4">Admin</span>
        </a>
    </div>
    <div style="color: lightgray">
        @User.Identity?.Name
    </div>
    <div class="block lg:hidden">
        <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20">
                <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>

    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
        <ul class="list-reset lg:flex justify-end flex-1 items-center font-bold">
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline hover:fo hover:text-gray-200 py-2 px-4" asp-controller="Movie" asp-action="MovieList">Films</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline hover:text-gray-200 py-2 px-4" asp-controller="Show" asp-action="ShowList">Shows</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="Cinema" asp-action="CinemaList">Cinemas</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="Discount" asp-action="DiscountList">Discounts</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="Ticket" asp-action="TicketList">Tickets</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="Producer" asp-action="ProducerList">Producers</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="TheaterMember" asp-action="MemberList">Members</a>
            </li>
            <li class="mr-3">
                <a class="inline-block text-red-600 no-underline  hover:text-gray-200 py-2 px-4" asp-controller="TheaterUser" asp-action="UserList">Users</a>
            </li>
            @if (_signInManager.IsSignedIn(User))
            {
                <li class="mr-3">
                    <a class="inline-block text-red-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" asp-controller="TheaterUser" asp-action="Logout">Log out</a>
                </li>
            }
            else
            {
                <li class="mr-3">
                    <a class="inline-block text-red-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" asp-controller="TheaterUser" asp-action="Login">Log in</a>
                </li>
            }
        </ul>
    </div>
</nav>
<div class="w-full h-full content shadow-lg mx-auto mt-24 md:mt-18 bg-cover bg-fixed">
    @RenderBody()
</div>
<script>
        //Javascript to toggle the menu
        document.getElementById('nav-toggle').onclick = function () {
            document.getElementById("nav-content").classList.toggle("hidden");
        }
    </script>
<script src="~/js/main.js"></script>
</body>
</html>